shell:
  program: /bin/bash # default shell (zsh) will still be launched in tmux
  args:
    - -l
    - -c
    - "tmux"
window:
  # startup_mode: Maximized
  # https://github.com/alacritty/alacritty/issues/6397#issuecomment-1375552591
  dimensions:
    columns: 240
    lines: 160
