[window]
startup_mode = "Maximized"

[font.normal]
family = "Hack Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style  = "Italic"

[env]
TERM = "xterm-256color"

# nvim --headless -c "Dunkel colorscheme dark-kontrast alacritty" -c "qa"
[colors]
selection = { background = '#ababab', text = '#101010' }

[colors.bright]
black = '#ababab'
blue = '#eeeeee'
cyan = '#eeeeee'
green = '#a0d17b'
magenta = '#f29c5f'
red = '#e26f60'
white = '#ece9df'
yellow = '#f29c5f'

[colors.normal]
black = '#101010'
blue = '#eeeeee'
cyan = '#eeeeee'
green = '#a0d17b'
magenta = '#f29c5f'
red = '#e26f60'
white = '#ece9df'
yellow = '#f29c5f'

[colors.primary]
background = '#181818'
foreground = '#fdd291'

[colors.search]
matches = { background = '#ababab', foreground = '#101010' }
focused_match = { background = '#ece9df', foreground = '#101010' }
